"""
Tests for Zcash client — Generated by Zcash Migrate

Tests ZebraRPC (zebrad JSON-RPC) and ZkoolWallet (zkool GraphQL) separately.
Run: pytest test_zcash_rpc.py -v

Requires:
  - zebrad running on port 8232 (or ZEBRA_PORT env var)
  - zkool_graphql running on port 8000 (or ZKOOL_PORT env var)
"""
import os
import pytest
from zcash_rpc import ZebraRPC, ZkoolWallet, ZcashClient


# ─── Fixtures ────────────────────────────────────────────────────────

@pytest.fixture
def zebra():
    return ZebraRPC(
        host=os.environ.get("ZEBRA_HOST", "127.0.0.1"),
        port=int(os.environ.get("ZEBRA_PORT", "8232")),
        user=os.environ.get("ZEBRA_USER", ""),
        password=os.environ.get("ZEBRA_PASSWORD", ""),
    )


@pytest.fixture
def zkool():
    return ZkoolWallet(
        host=os.environ.get("ZKOOL_HOST", "127.0.0.1"),
        port=int(os.environ.get("ZKOOL_PORT", "8000")),
    )


@pytest.fixture
def client():
    return ZcashClient()


# ─── ZebraRPC tests (chain data via zebrad) ──────────────────────────

class TestZebraRPC:
    def test_getblockchaininfo(self, zebra):
        info = zebra.getblockchaininfo()
        assert "chain" in info
        assert "blocks" in info

    def test_getbestblockhash(self, zebra):
        hash_ = zebra.getbestblockhash()
        assert isinstance(hash_, str)
        assert len(hash_) == 64  # 32 bytes hex

    def test_getblock(self, zebra):
        hash_ = zebra.getbestblockhash()
        block = zebra.getblock(hash_, verbosity=1)
        assert "height" in block
        assert "tx" in block

    def test_getblock_by_height(self, zebra):
        block = zebra.getblock(1, verbosity=1)
        assert block["height"] == 1

    def test_z_validateaddress_transparent(self, zebra):
        # t1 mainnet transparent address format check
        result = zebra.z_validateaddress("t1Hsc1LR8yKnbbe3twRp88p6vFfC87hPDFp")
        assert "isvalid" in result

    def test_z_validateaddress_invalid(self, zebra):
        result = zebra.z_validateaddress("invalid_address_xyz")
        assert result.get("isvalid") is False

    def test_getaddressbalance(self, zebra):
        # Query balance for a known address (may be 0)
        result = zebra.getaddressbalance(["t1Hsc1LR8yKnbbe3twRp88p6vFfC87hPDFp"])
        assert "balance" in result

    def test_z_listunifiedreceivers(self, zebra):
        # This test requires a valid UA — skip if no UA available
        # Just verify the method exists and handles errors
        with pytest.raises(Exception):
            zebra.z_listunifiedreceivers("not_a_unified_address")


# ─── ZkoolWallet tests (wallet ops via zkool_graphql) ────────────────

class TestZkoolWallet:
    @pytest.mark.skipif(
        not os.environ.get("ZKOOL_TEST_ACCOUNT"),
        reason="Set ZKOOL_TEST_ACCOUNT=1 to run wallet tests (requires zkool_graphql)",
    )
    def test_create_account(self, zkool):
        result = zkool.create_account(
            name="test-account",
            key=os.environ.get("ZKOOL_TEST_KEY", "abandon " * 23 + "art"),
            pools=7,  # all pools
        )
        assert result is not None

    @pytest.mark.skipif(
        not os.environ.get("ZKOOL_TEST_ACCOUNT"),
        reason="Set ZKOOL_TEST_ACCOUNT=1 to run wallet tests",
    )
    def test_sync(self, zkool):
        account_id = int(os.environ.get("ZKOOL_ACCOUNT_ID", "1"))
        result = zkool.sync(account_id)
        assert result is not None

    @pytest.mark.skipif(
        not os.environ.get("ZKOOL_TEST_ACCOUNT"),
        reason="Set ZKOOL_TEST_ACCOUNT=1 to run wallet tests",
    )
    def test_get_balance(self, zkool):
        account_id = int(os.environ.get("ZKOOL_ACCOUNT_ID", "1"))
        result = zkool.get_balance(account_id)
        data = result.get("balanceByAccount", {})
        assert "transparent" in data
        assert "sapling" in data
        assert "orchard" in data
        assert "total" in data

    @pytest.mark.skipif(
        not os.environ.get("ZKOOL_TEST_ACCOUNT"),
        reason="Set ZKOOL_TEST_ACCOUNT=1 to run wallet tests",
    )
    def test_get_addresses(self, zkool):
        account_id = int(os.environ.get("ZKOOL_ACCOUNT_ID", "1"))
        result = zkool.get_addresses(account_id, pools=6)
        data = result.get("addressByAccount", {})
        assert "ua" in data  # Unified Address (u1...)

    @pytest.mark.skipif(
        not os.environ.get("ZKOOL_TEST_ACCOUNT"),
        reason="Set ZKOOL_TEST_ACCOUNT=1 to run wallet tests",
    )
    def test_get_notes(self, zkool):
        account_id = int(os.environ.get("ZKOOL_ACCOUNT_ID", "1"))
        result = zkool.get_notes(account_id)
        assert "notesByAccount" in result

    @pytest.mark.skipif(
        not os.environ.get("ZKOOL_TEST_ACCOUNT"),
        reason="Set ZKOOL_TEST_ACCOUNT=1 to run wallet tests",
    )
    def test_get_transactions(self, zkool):
        account_id = int(os.environ.get("ZKOOL_ACCOUNT_ID", "1"))
        result = zkool.get_transactions(account_id)
        assert "transactionsByAccount" in result


class TestZkoolSend:
    @pytest.mark.skipif(
        not os.environ.get("ZKOOL_TEST_SEND"),
        reason="Set ZKOOL_TEST_SEND=1 to run send tests (requires funded account)",
    )
    def test_send(self, zkool):
        account_id = int(os.environ.get("ZKOOL_ACCOUNT_ID", "1"))
        to_addr = os.environ.get("ZKOOL_TEST_RECIPIENT", "")
        assert to_addr, "Set ZKOOL_TEST_RECIPIENT env var"
        result = zkool.send(
            account_id=account_id,
            recipients=[{"address": to_addr, "amount": 0.0001}],
            src_pools=4,  # Orchard preferred
        )
        assert result is not None


# ─── ZcashClient unified facade ─────────────────────────────────────

class TestZcashClient:
    def test_client_has_chain_and_wallet(self, client):
        assert hasattr(client, "chain")
        assert hasattr(client, "wallet")
        assert isinstance(client.chain, ZebraRPC)
        assert isinstance(client.wallet, ZkoolWallet)

    def test_chain_via_client(self, client):
        info = client.chain.getblockchaininfo()
        assert "chain" in info
