"""
Zcash Client — Generated by Zcash Migrate

Architecture:
  - ZebraRPC: connects to zebrad (JSON-RPC, port 8232) for chain data.
    zebrad is a Zcash node — it serves blockchain state but has NO wallet.
  - ZkoolWallet: connects to zkool_graphql (GraphQL, port 8000) for wallet ops.
    zkool handles account creation, syncing, address generation, and the
    'pay' mutation which builds Orchard/Halo2 proofs and broadcasts txs.
  - ZcashClient: unified facade combining both.

Shielded Pools:
  - Transparent (pool=1): public, like Bitcoin. Addresses start with t1/t3.
  - Sapling (pool=2): zk-SNARK (Groth16). Addresses start with zs...
  - Orchard (pool=4): zk-SNARK (Halo2). No trusted setup. Latest pool.
    Orchard addresses are embedded in Unified Addresses (u1...).
  - Pool bitmask: 1=transparent, 2=sapling, 4=orchard, 6=sapling+orchard, 7=all.

Zero dependencies — uses only Python stdlib (urllib, json, base64).
"""
import json
import base64
import urllib.request
import urllib.error


class ZebraRPC:
    """JSON-RPC client for zebrad (chain data only, no wallet RPCs).

    zebrad serves blockchain state: blocks, transactions, address balances
    (transparent only), and address validation. It does NOT manage keys,
    accounts, or shielded balances — those are handled by ZkoolWallet.

    Default port: 8232 (mainnet), 18232 (testnet).
    """

    def __init__(self, host="127.0.0.1", port=8232, user="", password="", timeout=30):
        self.url = f"http://{host}:{port}"
        self.auth = f"{user}:{password}"
        self.timeout = timeout
        self._id = 0

    def call(self, method: str, params=None):
        """Execute a JSON-RPC call to zebrad."""
        self._id += 1
        payload = json.dumps({
            "jsonrpc": "2.0",
            "id": self._id,
            "method": method,
            "params": params or [],
        }).encode("utf-8")

        req = urllib.request.Request(self.url, data=payload)
        req.add_header("Content-Type", "application/json")
        if self.auth.strip(":"):
            auth_bytes = self.auth.encode("utf-8")
            req.add_header("Authorization", f"Basic {base64.b64encode(auth_bytes).decode()}")

        try:
            with urllib.request.urlopen(req, timeout=self.timeout) as resp:
                result = json.loads(resp.read().decode("utf-8"))
                if result.get("error"):
                    raise Exception(f"RPC error: {result['error']}")
                return result.get("result")
        except urllib.error.HTTPError as e:
            body = e.read().decode("utf-8", errors="replace")
            raise Exception(f"HTTP {e.code}: {body}")

    # ─── Chain state ─────────────────────────────────────────────────

    def getblockchaininfo(self):
        """Get current chain info: network, blocks, best block hash, etc."""
        return self.call("getblockchaininfo")

    def getbestblockhash(self):
        """Get the hash of the best (most recent) block."""
        return self.call("getbestblockhash")

    def getblock(self, hash_or_height, verbosity=1):
        """Get block data. verbosity: 0=hex, 1=json, 2=json+tx details."""
        return self.call("getblock", [str(hash_or_height), verbosity])

    def getrawtransaction(self, txid: str, verbose=1):
        """Get raw transaction. verbose=1 returns decoded JSON."""
        return self.call("getrawtransaction", [txid, verbose])

    def sendrawtransaction(self, hex_string: str):
        """Broadcast a raw transaction hex to the network."""
        return self.call("sendrawtransaction", [hex_string])

    # ─── Transparent address queries (no wallet needed) ──────────────

    def getaddressbalance(self, addresses: list):
        """Get transparent balance for one or more t-addresses.
        Returns {"balance": <zatoshis>}. 1 ZEC = 100_000_000 zatoshis.
        NOTE: This only reports transparent funds. For shielded balances,
        use ZkoolWallet.get_balance().
        """
        return self.call("getaddressbalance", [{"addresses": addresses}])

    def getaddresstxids(self, addresses: list, start: int, end: int):
        """Get transaction IDs for transparent addresses in block range."""
        return self.call("getaddresstxids", [{"addresses": addresses, "start": start, "end": end}])

    # ─── Address validation and decomposition ────────────────────────

    def z_validateaddress(self, address: str):
        """Validate any Zcash address (transparent, sapling, or unified).
        Returns {isvalid, address_type, ...}.
        """
        return self.call("z_validateaddress", [address])

    def z_listunifiedreceivers(self, unified_address: str):
        """Decompose a Unified Address (u1...) into its pool receivers.
        Returns {orchard: "...", sapling: "...", p2pkh: "..."} depending
        on which pools the UA encodes.
        """
        return self.call("z_listunifiedreceivers", [unified_address])


class ZkoolWallet:
    """GraphQL client for zkool_graphql (wallet operations).

    zkool_graphql manages HD accounts, address derivation, note tracking,
    and transaction construction with Orchard (Halo2) proof generation.
    The key mutation is 'pay' — it selects notes, builds the tx, generates
    the zk proof, and broadcasts via zebrad in one call.

    Default port: 8000.
    """

    def __init__(self, host="127.0.0.1", port=8000, timeout=60):
        self.url = f"http://{host}:{port}/graphql"
        self.timeout = timeout

    def _query(self, query: str, variables=None):
        """Execute a GraphQL query/mutation against zkool_graphql."""
        payload = json.dumps({
            "query": query,
            "variables": variables or {},
        }).encode("utf-8")

        req = urllib.request.Request(self.url, data=payload)
        req.add_header("Content-Type", "application/json")

        try:
            with urllib.request.urlopen(req, timeout=self.timeout) as resp:
                result = json.loads(resp.read().decode("utf-8"))
                if result.get("errors"):
                    msgs = "; ".join(e.get("message", "") for e in result["errors"])
                    raise Exception(f"GraphQL error: {msgs}")
                return result.get("data")
        except urllib.error.HTTPError as e:
            body = e.read().decode("utf-8", errors="replace")
            raise Exception(f"HTTP {e.code}: {body}")

    # ─── Account management ──────────────────────────────────────────

    def create_account(self, name: str, key: str, pools=7):
        """Create a new HD wallet account.

        Args:
            name: Human-readable account label.
            key: Seed phrase or spending key.
            pools: Bitmask of pools to activate.
                   1=transparent, 2=sapling, 4=orchard, 7=all.
                   Default 7 activates all pools.

        Returns:
            Account ID (int).
        """
        return self._query(
            """mutation CreateAccount($name: String!, $key: String!, $pools: Int!) {
              createAccount(name: $name, key: $key, pools: $pools)
            }""",
            {"name": name, "key": key, "pools": pools},
        )

    def sync(self, account_id: int):
        """Synchronize account with the blockchain.
        Downloads and trial-decrypts blocks to find notes belonging
        to this account. Must be called before get_balance/get_notes.
        """
        return self._query(
            """mutation Synchronize($idAccount: Int!) {
              synchronize(idAccount: $idAccount)
            }""",
            {"idAccount": account_id},
        )

    # ─── Balance and addresses ───────────────────────────────────────

    def get_balance(self, account_id: int):
        """Get shielded + transparent balance for an account.

        Returns:
            {transparent, sapling, orchard, total} in ZEC (float).
        """
        return self._query(
            """query BalanceByAccount($idAccount: Int!) {
              balanceByAccount(idAccount: $idAccount) {
                transparent
                sapling
                orchard
                total
              }
            }""",
            {"idAccount": account_id},
        )

    def get_addresses(self, account_id: int, pools=6):
        """Get addresses for an account.

        Args:
            account_id: Account ID.
            pools: Bitmask of pools. Default 6 = sapling+orchard (shielded only).
                   Use 4 for Orchard-only UA, 7 for all pools.

        Returns:
            {ua, transparent, sapling, orchard} — the UA (u1...) is the
            primary address; individual pool addresses are also returned.
        """
        return self._query(
            """query AddressByAccount($idAccount: Int!, $pools: Int!) {
              addressByAccount(idAccount: $idAccount, pools: $pools) {
                ua
                transparent
                sapling
                orchard
              }
            }""",
            {"idAccount": account_id, "pools": pools},
        )

    def new_addresses(self, account_id: int):
        """Derive new addresses for an account (rotates diversifier).
        Returns new address set.
        """
        return self._query(
            """mutation NewAddresses($idAccount: Int!) {
              newAddresses(idAccount: $idAccount) {
                ua
                transparent
                sapling
                orchard
              }
            }""",
            {"idAccount": account_id},
        )

    # ─── Transactions ────────────────────────────────────────────────

    def send(self, account_id: int, recipients: list, src_pools=7):
        """Send ZEC to one or more recipients.

        This is the key operation — zkool builds the transaction, generates
        Orchard (Halo2) or Sapling (Groth16) zk-SNARK proofs, and broadcasts
        the transaction through zebrad. Proof generation is CPU-intensive
        (~2-5 seconds for Orchard).

        Args:
            account_id: Source account ID.
            recipients: List of dicts, each with:
                - address (str): Recipient address (t1..., zs..., or u1...).
                - amount (float): Amount in ZEC.
                - memo (str, optional): Up to 512 bytes, shielded only.
            src_pools: Bitmask of source pools to spend from.
                       4=orchard (preferred), 7=any pool.

        Returns:
            Transaction ID (txid) string.
        """
        return self._query(
            """mutation Pay($idAccount: Int!, $recipients: [RecipientInput!]!, $srcPools: Int!) {
              pay(idAccount: $idAccount, recipients: $recipients, srcPools: $srcPools)
            }""",
            {"idAccount": account_id, "recipients": recipients, "srcPools": src_pools},
        )

    def get_notes(self, account_id: int):
        """Get unspent notes (shielded UTXOs) for an account.
        Notes are the shielded equivalent of UTXOs — they are encrypted
        on-chain and only visible to the account holder.
        """
        return self._query(
            """query NotesByAccount($idAccount: Int!) {
              notesByAccount(idAccount: $idAccount) {
                id
                amount
                pool
                spent
              }
            }""",
            {"idAccount": account_id},
        )

    def get_transactions(self, account_id: int):
        """Get transaction history for an account."""
        return self._query(
            """query TransactionsByAccount($idAccount: Int!) {
              transactionsByAccount(idAccount: $idAccount) {
                txid
                amount
                height
                timestamp
                pool
              }
            }""",
            {"idAccount": account_id},
        )


class ZcashClient:
    """Unified Zcash client combining zebrad (chain) and zkool (wallet).

    Usage:
        client = ZcashClient()
        # Chain data via zebrad:
        info = client.chain.getblockchaininfo()
        # Wallet ops via zkool:
        client.wallet.sync(account_id=1)
        bal = client.wallet.get_balance(account_id=1)
    """

    def __init__(self, zebra_host="127.0.0.1", zebra_port=8232,
                 zkool_host="127.0.0.1", zkool_port=8000,
                 rpc_user="", rpc_password=""):
        self.chain = ZebraRPC(host=zebra_host, port=zebra_port,
                              user=rpc_user, password=rpc_password)
        self.wallet = ZkoolWallet(host=zkool_host, port=zkool_port)
